services:

  init-geth:
    image: ghcr.io/depinfra/geth 
    command: >
       --datadir=/execution-data init /config/genesis.json

    volumes:
      - ./data/execution-data:/execution-data
      - ../config:/config

  geth:
    image: ghcr.io/depinfra/geth 
    depends_on:
      - init-geth
    command:
      - --networkid=${NETWORK_ID}
      - --state.scheme=path
      - --verbosity=3
      - --datadir=/execution-data
      - --nat=extip:${NODE_PUBLIC_IP}
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api=admin,engine,net,eth,web3,debug,txpool
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=admin,engine,net,eth,web3,debug,txpool
      - --ws.origins=*
      - --allow-insecure-unlock
      - --authrpc.port=8551
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/config/jwtsecret
      - --syncmode=full
      - --rpc.allow-unprotected-txs
      - --bootnodes=${EL_NODES}
    volumes:
      - ./data/execution-data:/execution-data
      - ../config:/config
    ports:
      - "8545:8545"
      - "30303:30303"
    restart: unless-stopped

  beacon:
#    image: sigp/lighthouse:v5.3.0
    image: ethpandaops/lighthouse:pawan-electra-alpha7-b2b728d
    command:
      - lighthouse
      - beacon_node
      - --disable-peer-scoring
      - --disable-packet-filter
      - --staking
      - --http 
      - --http-address=0.0.0.0
      - --http-port=5052
      - --enr-address=${NODE_PUBLIC_IP}
      - --enr-udp-port=9000
      - --enr-tcp-port=9000
      - --validator-monitor-auto
      - --http-allow-origin=*
      - --listen-address=0.0.0.0
      - --port=9000
      - --target-peers=100
      - --testnet-dir=/config
      - --execution-endpoints=http://geth:8551
      - --jwt-secrets=/config/jwtsecret
      - --suggested-fee-recipient=${FEE_RECIPIENT}
      - --prune-blobs=false
      - --allow-insecure-genesis-sync
      - --boot-nodes=${CL_NODES}
      - --disable-optimistic-finalized-sync
    volumes:
      - ./data/consensus-data:/root/.lighthouse
      - ../config:/config
    depends_on:
      - geth
    ports:
      - "9000:9000"
      - "5052:5052"
    restart: unless-stopped

